version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: my-apache-app
    restart: unless-stopped
    ports:
    - '8080:80'
    volumes:
    - ./htdocs:/usr/local/apache2/htdocs
networks:
  default:
    name: vortex-bridge
    external: true
