version: '3'

# networks
networks:
  mysql_network:
    driver: bridge

services:
  # MySQL8
  mysql:
    container_name: mysql8
    image: mysql:8.0.32
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-file=/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: p4ass0rd_root
      MYSQL_DATABASE: vortex_backend
      MYSQL_USER: vortex
      MYSQL_PASSWORD: vortexp4assword
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3408:3306
    restart: unless-stopped
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './db/sql:/docker-entrypoint-initdb.d'
    networks:
      - mysql_network
